using System;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using QuickCollab.Collaboration.Domain.Models;
using QuickCollab.Collaboration.Domain.Exceptions;
using QuickCollab.Collaboration.Domain.Events;

namespace QuickCollab.Collaboration.Domain.Tests
{
    [TestClass]
    public class PartyAggregateTests
    {
        [TestMethod]
        public void ShouldAdmitPassForNonSecuredParty()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(1);
            Party party = CreateNonSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId);

            Event ev = party.GetUncommittedChanges().Single();

            Assert.IsInstanceOfType(ev, typeof(PassRegistered));
            Assert.AreEqual(true, party.EnsureAdmission(passId));
        }

        [TestMethod]
        public void ShouldAdmitPassForSecuredParty()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(1);
            Party party = CreateSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId, "SecretPassword");

            Event ev = party.GetUncommittedChanges().Single();

            Assert.IsInstanceOfType(ev, typeof(PassRegistered));
            Assert.AreEqual(true, party.EnsureAdmission(passId));
            Assert.AreEqual(true, party.EnsureAdmission(passId));
        }

        [TestMethod]
        [ExpectedException(typeof(NotAuthorizedException))]
        public void ShouldRejectPassForSecuredParty()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(1);
            Party party = CreateSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId, "WrongPassword");
        }

        [TestMethod]
        [ExpectedException(typeof(InvalidOperationException))]
        public void ShouldThrowExceptionWhenNoPasswordProvided()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(1);
            Party party = CreateSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId);
        }

        [TestMethod]
        [ExpectedException(typeof(PartyExpiredException))]
        public void ShouldThrowExceptionWhenNonSecuredPartyExceededExpiryDate()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(-1);
            Party party = CreateNonSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId);
        }

        [TestMethod]
        [ExpectedException(typeof(PartyExpiredException))]
        public void ShouldThrowExceptionWhenSecuredPartyExceededExpiryDate1()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(-1);
            Party party = CreateSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            // Throws error despite correct password
            party.Register(passId, "SecretPassword");
        }

        [TestMethod]
        [ExpectedException(typeof(PartyExpiredException))]
        public void ShouldThrowExceptionWhenSecuredPartyExceededExpiryDate2()
        {
            DateTime expiryDate = DateTime.UtcNow.AddHours(-1);
            Party party = CreateSecuredParty(expiryDate);
            PassId passId = CreatePassId();

            party.Register(passId, "WrongPassword");
        }

        #region Helper Methods

        private Party CreateNonSecuredParty(DateTime expiryDate)
        {
            // id generated by system
            string id = Guid.NewGuid().ToString();

            PartyDetails details = new PartyDetails("MyParty", expiryDate);

            return new Party(id, details);
        }

        private Party CreateSecuredParty(DateTime expiryDate)
        {
            // id generated by system
            string id = Guid.NewGuid().ToString();

            PartyDetails details = new PartyDetails("MyParty", expiryDate);
            Secret secret = new Secret("SecretPassword");

            return new Party(id, details, secret);
        }

        private PassId CreatePassId()
        {
            // id generated by system
            string passId = Guid.NewGuid().ToString();
            return new PassId(passId);
        }

        #endregion
    }
}
